
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloObjis", targetNamespace = "http://SERVICE.ensup.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloObjis {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bonjour", targetNamespace = "http://SERVICE.ensup.eu/", className = "client.Bonjour")
    @ResponseWrapper(localName = "bonjourResponse", targetNamespace = "http://SERVICE.ensup.eu/", className = "client.BonjourResponse")
    @Action(input = "http://SERVICE.ensup.eu/HelloObjis/bonjourRequest", output = "http://SERVICE.ensup.eu/HelloObjis/bonjourResponse")
    public String bonjour(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
